# Generated by Django 2.2.13 on 2020-09-24 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0007_exercise_cover'),
        ('checkout', '0002_auto_20200924_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mealplan_Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now=True)),
                ('price', models.PositiveIntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mealplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Mealplan')),
            ],
        ),
    ]
