# Generated by Django 2.2.13 on 2020-09-09 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_mealplan'),
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealplanReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('datetime', models.DateTimeField()),
                ('mealplan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.Mealplan')),
            ],
        ),
    ]
