# Generated by Django 2.2.13 on 2020-09-09 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_auto_20200909_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisereview',
            name='datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
