# Generated by Django 2.2.13 on 2020-09-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_auto_20200909_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisereview',
            name='content',
            field=models.TextField(max_length=255),
        ),
    ]
