# Generated by Django 2.2.13 on 2020-09-09 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_auto_20200909_0754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplanreview',
            name='content',
            field=models.TextField(max_length=255),
        ),
    ]
