# Generated by Django 2.2.13 on 2020-09-09 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer'),
        ),
    ]
