# Generated by Django 2.2.13 on 2020-09-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20200909_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.PositiveIntegerField(),
        ),
    ]
