# Generated by Django 2.2.13 on 2020-09-09 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_mealplan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealplan',
            name='price',
            field=models.PositiveIntegerField(),
        ),
    ]
