# Generated by Django 2.2.13 on 2020-09-23 09:17

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200909_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='cover',
            field=cloudinary.models.CloudinaryField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
